name: Build Android Mod APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradle
      run: chmod +x TemplateModMenu/gradlew

    - name: Build with Gradle
      run: |
        cd TemplateModMenu
        ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Trickcal-Mod-APK
        path: TemplateModMenu/app/build/outputs/apk/debug/*.apk
